name: '.NET nanoFramework dependencies updater'
description: 'Updates .NET nanoFramework NuGet packages and nuspec files on .NET nanoFramework solutions'
author: '.NET nanoFramework Contributors'
branding:
  icon: git-merge
  color: purple
inputs:
  workingDirectory:
    required: false
    description: 'Repo root|Working directory. Use when targeting Solution file(s) other than the repository root.'
    default: '${{ github.workspace }}'
  stablePackages:
    required: false
    description: 'Use stable NuGet package versions.'
    default: 'false'
  previewPackages:
    required: false
    description: 'Use preview NuGet package versions.'
    default: 'true'
  solutionsToCheck:
    required: false
    description: 'List of Solution(s) to update in the `workingDirectory` directory.'
    default: ''
  reposToUpdate:
    required: false
    description: 'List of repository(es) to update.'
    default: ''
  exclusionList:
    required: false
    description: 'List of solution names to exclude from the update. Comma separated, name only.'
    default: ''
  branchToPr:
    required: false
    description: 'Branch name to submit PR with update. Default is `develop`.'
    default: 'develop'
runs:
  using: 'node12'
  main: 'dist/index.js'
