# `dist/index.js` is a special file in Actions.
# When you reference an action with `uses:` in a workflow,
# `index.js` is the code that will run.
# For our project, we generate this file through a build process from other source files.
# We need to make sure the checked-in `index.js` actually matches what we expect it to be.
name: Check update compatibility

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  check-dist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x # if possible should use `lts/*`
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build lib
        run: npm run build

      - name: Check Update compatiility with `dist/index.js`
        # Ensure no changes with `dist/index.js`.
        run: |
          git add -u . # compare after applying git EOL normalization
          git diff --cached --exit-code --stat \
          || (echo "##[error] found changed files after build in CI." \
                  "Please 'yarn run build' locally and check in all changes" \
              && git diff --cached \
              && exit 1)

  test:
    runs-on: ubuntu-latest
    needs: check-dist
    steps:

    - uses: actions/checkout@v3
      with:
        ref: 'main' 

    - name: nanodu failing packages options
      uses: ./
      continue-on-error: true
      with:
        stablePackages: true
        previewPackages: true
  
    - name: nanodu failing repos and solutions options
      uses: ./
      continue-on-error: true
      with:
        solutionsToCheck: ''
        reposToUpdate: ''
