# `dist/index.js` is a special file in Actions.
# When you reference an action with `uses:` in a workflow,
# `index.js` is the code that will run.
# For our project, we generate this file through a build process from other source files.
# We need to make sure the checked-in `index.js` actually matches what we expect it to be.
name: Check dist/

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  check-dist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js lts
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: npm run build
        run: npm run build

      - name: check for uncommitted changes
        # Ensure no changes.
        run: |
          git add -u . # compare after applying git EOL normalization
          git diff --cached --exit-code --stat \
          || (echo "##[error] found changed files after build. please 'yarn run build'" \
                  "and check in all changes" \
              && git diff --cached \
              && exit 1)

      # - name: Run Sonar Scan
      #   continue-on-error: true
      #   uses: sonarsource/sonarcloud-github-action@master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      #     SONAR_TOKEN: ${{ secrets.sonar_token }}

  test:
    runs-on: ubuntu-latest
    needs: check-dist
    steps:

    - uses: actions/checkout@v3
      with:
        ref: 'main' 

    - name: nanodu failing packages options
      uses: ./
      continue-on-error: true
      with:
        stablePackages: true
        previewPackages: true
    - name: nanodu failing repos and solutions options
      uses: ./
      continue-on-error: true
      with:
        solutionsToCheck: ''
        reposToUpdate: ''
