name: Release

on:
  push:
    tags:
      - v*

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - run: '! [[ $GITHUB_REF =~ -release$ ]]'
      - run: '! [[ ${GITHUB_REF:10} =~ ^v[0-9]+$ ]]'

  release:
    runs-on: ubuntu-latest
    needs: check-dist
    steps:
      - uses: actions/checkout@v3
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false